name: fitmate
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0" # Fixed SDK constraint format

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8

#   # Firebase dependencies
#   firebase_core: ^3.8.0
#   firebase_auth: ^5.3.3
#   firebase_auth_web: ^5.13.4
#   cloud_firestore: ^5.5.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   firebase_auth_mocks: ^0.14.1
#   mockito: ^5.4.0
#   fake_cloud_firestore: ^3.1.0
#   build_runner: ^2.4.0
#   test: any
#   google_fonts: ^6.2.1
#   flutter_lints: ^5.0.0
#   firebase_core_platform_interface: ^5.0.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.17.5
  firebase_auth: ^4.20.0
  firebase_auth_web: ^5.12.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.4
  http: ^1.3.0
  camera: ^0.10.0
  lottie: ^2.3.2
  flutter_riverpod: ^2.0.0
  # Choose only one TFLite solution (removing conflicting dependencies)
  # tflite: ^1.1.2  # Keep this as your primary TFLite package
  # tflite_flutter: ^0.11.0  # Commented out to avoid conflicts
  typed_data: ^1.3.2
  path_provider: ^2.0.15 # For file handling
  image: ^4.0.17 # For image processing
  vector_math: ^2.1.4 # For mathematical operations
  google_ml_kit: ^0.16.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  provider: ^6.0.5 # Added for state management
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.3
  http_parser: ^4.1.2
  firebase_storage: ^11.7.7
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  build_runner: ^2.4.8
  test: ^1.24.9
  google_fonts: ^6.1.0 #this is listed twice -> remove ??
  flutter_lints: ^3.0.1
  firebase_core_platform_interface: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/images/fit_robot.png
    - assets/data/images/strawberry.png
    - assets/data/images/workouts/image 2.png
    - assets/data/images/workouts/image 22.png
    - assets/data/images/workouts/image 33.png
    - assets/data/images/workouts/image 55.png
    - assets/data/images/workouts/image 3.png
    - assets/data/images/workouts/image 4.png
    - assets/data/images/workouts/image 5.png
    - assets/data/images/yoga-pose.png
    - assets/data/images/avatar/av1.png
    - assets/data/images/avatar/av2.png
    - assets/data/images/avatar/av3.png
    - assets/data/images/avatar/av4.png
    - assets/data/images/avatar/av5.png
    - assets/data/images/avatar/av6.png
    - assets/data/images/avatar/av7.png
    - assets/data/images/avatar/av8.png
    - assets/data/images/avatar/av9.png
    - assets/data/images/avatar/av10.png
    - assets/data/images/avatar/av11.png
    - assets/data/images/avatar/av12.png
    - assets/data/images/avatar/av13.png
    - assets/data/images/avatar/av14.png
    - assets/data/lottie/1.json
    - assets/data/lottie/2.json
    - assets/data/lottie/3.json
    - assets/data/lottie/4.json
    - assets/data/lottie/5.json
    - assets/data/lottie/6.json
    - assets/data/lottie/8.json
    - assets/data/images/easter-eggs/eg1.jpeg
    - assets/data/images/easter-eggs/eg2.jpeg
    - assets/data/images/easter-eggs/eg3.jpeg
    - assets/data/images/easter-eggs/eg4.jpeg
    - assets/data/images/easter-eggs/eg5.jpeg
    - assets/data/audio/sad-hamster.mp3


