// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     return const FirebaseOptions(
//       apiKey: 'test-api-key',
//       appId: 'test-app-id',
//       messagingSenderId: 'test-sender-id',
//       projectId: 'test-project-id',
//     );
//   }
// }
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjX_VwAA2Bce5h0MgAkgozPoVa4kyjKe0',
    appId: '1:1054731745412:web:9edeea8454b237b50a6ad1',
    messagingSenderId: '1054731745412',
    projectId: 'fitmate-98874',
    authDomain: 'fitmate-98874.firebaseapp.com',
    storageBucket: 'fitmate-98874.firebasestorage.app',
    measurementId: 'G-7PNW97TTD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3I6mQ6UoqcRg8QFcF7bfl0k79UaR0MGA',
    appId: '1:1054731745412:android:b2f96b7c89d961750a6ad1',
    messagingSenderId: '1054731745412',
    projectId: 'fitmate-98874',
    storageBucket: 'fitmate-98874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFPVd4jVAWxz081PrBAwgeCvW4CGtT7-o',
    appId: '1:1054731745412:ios:5b57bed1fa5e4ca80a6ad1',
    messagingSenderId: '1054731745412',
    projectId: 'fitmate-98874',
    storageBucket: 'fitmate-98874.firebasestorage.app',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFPVd4jVAWxz081PrBAwgeCvW4CGtT7-o',
    appId: '1:1054731745412:ios:5b57bed1fa5e4ca80a6ad1',
    messagingSenderId: '1054731745412',
    projectId: 'fitmate-98874',
    storageBucket: 'fitmate-98874.firebasestorage.app',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjX_VwAA2Bce5h0MgAkgozPoVa4kyjKe0',
    appId: '1:1054731745412:web:04d906243acc80870a6ad1',
    messagingSenderId: '1054731745412',
    projectId: 'fitmate-98874',
    authDomain: 'fitmate-98874.firebaseapp.com',
    storageBucket: 'fitmate-98874.firebasestorage.app',
    measurementId: 'G-75MCMSZ372',
  );
}
